import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import { main } from "../src/main.ts";
import { handlePawCommand } from "../src/paw/init-command.ts";

const testDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(testDir, "..", "..", "..");
const sourceConfigPath = join(repoRoot, "paw-spec", "config.yaml");
const tempRoots: string[] = [];

let originalCwd: string;
let originalExitCode: typeof process.exitCode;

async function createTempProject(): Promise<string> {
	const root = await mkdtemp(join(tmpdir(), "paw-init-command-"));
	tempRoots.push(root);
	await mkdir(join(root, "paw-spec"), { recursive: true });
	await writeFile(join(root, "paw-spec", "config.yaml"), await readFile(sourceConfigPath, "utf-8"), "utf-8");
	return root;
}

beforeEach(() => {
	originalCwd = process.cwd();
	originalExitCode = process.exitCode;
	process.exitCode = undefined;
});

afterEach(async () => {
	vi.restoreAllMocks();
	process.chdir(originalCwd);
	process.exitCode = originalExitCode;
	await Promise.all(tempRoots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

describe("Paw init command", () => {
	test("initializes durable .paw files from paw-spec/config.yaml", async () => {
		const projectRoot = await createTempProject();
		process.chdir(projectRoot);
		const logSpy = vi.spyOn(console, "log").mockImplementation(() => {});

		await expect(handlePawCommand(["paw", "init"])).resolves.toBe(true);

		expect(await readFile(join(projectRoot, ".paw", "config.yaml"), "utf-8")).toContain("version:");
		expect(await readFile(join(projectRoot, ".paw", "version"), "utf-8")).toMatch(/\S+\n/);
		expect(await readFile(join(projectRoot, ".paw", "memory", "memories.yaml"), "utf-8")).toBe("memories: []\n");
		expect(await readFile(join(projectRoot, ".paw", ".gitignore"), "utf-8")).toContain("# Generated by paw init.");
		const stdout = logSpy.mock.calls.map(([message]) => String(message)).join("\n");
		expect(stdout).toContain(".paw initialized");
		expect(stdout).toContain("created: 8");
		expect(stdout).toContain("existing: 0");
		expect(process.exitCode).toBeUndefined();
	});

	test("preserves an edited durable config file on repeated init", async () => {
		const projectRoot = await createTempProject();
		process.chdir(projectRoot);
		vi.spyOn(console, "log").mockImplementation(() => {});

		await expect(handlePawCommand(["paw", "init"])).resolves.toBe(true);
		await writeFile(join(projectRoot, ".paw", "config.yaml"), "custom: true\n", "utf-8");
		await expect(handlePawCommand(["paw", "init"])).resolves.toBe(true);

		expect(await readFile(join(projectRoot, ".paw", "config.yaml"), "utf-8")).toBe("custom: true\n");
		expect(process.exitCode).toBeUndefined();
	});

	test("shows init help without creating .paw", async () => {
		const projectRoot = await createTempProject();
		process.chdir(projectRoot);
		const logSpy = vi.spyOn(console, "log").mockImplementation(() => {});

		await expect(handlePawCommand(["paw", "init", "--help"])).resolves.toBe(true);

		const stdout = logSpy.mock.calls.map(([message]) => String(message)).join("\n");
		expect(stdout).toContain("pi paw init");
		expect(existsSync(join(projectRoot, ".paw"))).toBe(false);
		expect(process.exitCode).toBeUndefined();
	});

	test("reports unknown Paw subcommands without throwing", async () => {
		const projectRoot = await createTempProject();
		process.chdir(projectRoot);
		const errorSpy = vi.spyOn(console, "error").mockImplementation(() => {});

		await expect(handlePawCommand(["paw", "not-a-real-command"])).resolves.toBe(true);

		const stderr = errorSpy.mock.calls.map(([message]) => String(message)).join("\n");
		expect(stderr).toContain("Unknown Paw command: not-a-real-command");
		expect(process.exitCode).toBe(1);
	});

	test("main routes paw init before normal agent runtime", async () => {
		const projectRoot = await createTempProject();
		process.chdir(projectRoot);
		vi.spyOn(console, "log").mockImplementation(() => {});
		vi.spyOn(process, "exit").mockImplementation(((code?: string | number | null) => {
			throw new Error(`process.exit(${code ?? ""})`);
		}) as typeof process.exit);

		await expect(main(["paw", "init"])).resolves.toBeUndefined();

		expect(await readFile(join(projectRoot, ".paw", "memory", "memories.yaml"), "utf-8")).toBe("memories: []\n");
		expect(process.exitCode).toBeUndefined();
	});
});
