import { randomUUID } from "node:crypto";
import { type FileHandle, mkdir, open, readFile, rename, stat, unlink } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";
import { stringify } from "yaml";
import type { PawRuntimeConfig } from "./contracts.ts";

export interface PawProjectPaths {
	repoRoot: string;
	pawDir: string;
	configFile: string;
	versionFile: string;
	memoryDir: string;
	memoriesFile: string;
	rulesDir: string;
	decisionsDir: string;
	gitignoreFile: string;
}

export interface PawInitResult {
	paths: PawProjectPaths;
	created: string[];
	existing: string[];
}

export interface PawAtomicWriteOptions {
	jsonIndent?: string | number;
}

interface FileSystemError extends Error {
	code?: string;
}

const DEFAULT_MEMORIES_YAML = "memories: []\n";

export function resolvePawProjectPaths(repoRoot: string): PawProjectPaths {
	const resolvedRoot = resolve(repoRoot);
	const pawDir = join(resolvedRoot, ".paw");
	const memoryDir = join(pawDir, "memory");

	return {
		repoRoot: resolvedRoot,
		pawDir,
		configFile: join(pawDir, "config.yaml"),
		versionFile: join(pawDir, "version"),
		memoryDir,
		memoriesFile: join(memoryDir, "memories.yaml"),
		rulesDir: join(pawDir, "rules"),
		decisionsDir: join(pawDir, "decisions"),
		gitignoreFile: join(pawDir, ".gitignore"),
	};
}

export function renderPawGitignore(config: PawRuntimeConfig): string {
	const lines = [
		"# Generated by paw init.",
		"# Durable paths intentionally left trackable:",
		...config.persistence.gitignore.commit.map((entry) => `# ${entry}`),
		"",
		...config.persistence.gitignore.ignore,
		"",
	];

	return lines.join("\n");
}

export async function initializePawProject(repoRoot: string, config: PawRuntimeConfig): Promise<PawInitResult> {
	const paths = resolvePawProjectPaths(repoRoot);
	const created: string[] = [];
	const existing: string[] = [];

	for (const dirPath of [paths.pawDir, paths.memoryDir, paths.rulesDir, paths.decisionsDir]) {
		await ensureDirectory(dirPath, created, existing);
	}

	await writeMissingFile(paths.configFile, stringify(config), created, existing);
	await writeMissingFile(paths.versionFile, `${config.version}\n`, created, existing);
	await writeMissingFile(paths.memoriesFile, DEFAULT_MEMORIES_YAML, created, existing);
	await writeMissingFile(paths.gitignoreFile, renderPawGitignore(config), created, existing);

	return { paths, created, existing };
}

export async function writePawJsonAtomic(
	filePath: string,
	value: unknown,
	options: PawAtomicWriteOptions = {},
): Promise<void> {
	const resolvedFile = resolve(filePath);
	const targetDir = dirname(resolvedFile);
	const tempFile = join(targetDir, `.${basename(resolvedFile)}.${process.pid}.${randomUUID()}.tmp`);
	const serialized = JSON.stringify(value, null, options.jsonIndent ?? "\t");

	if (serialized === undefined) {
		throw new Error("Cannot write undefined as JSON.");
	}

	await mkdir(targetDir, { recursive: true });

	let wroteTemp = false;
	try {
		const handle = await open(tempFile, "wx", 0o600);
		wroteTemp = true;
		try {
			await handle.writeFile(`${serialized}\n`, "utf-8");
			await handle.sync();
		} finally {
			await handle.close();
		}
		await rename(tempFile, resolvedFile);
		await syncDirectory(targetDir);
		wroteTemp = false;
	} finally {
		if (wroteTemp) {
			await removeTempFile(tempFile);
		}
	}
}

export async function readPawJson<T = unknown>(filePath: string): Promise<T> {
	return JSON.parse(await readFile(filePath, "utf-8")) as T;
}

async function ensureDirectory(dirPath: string, created: string[], existing: string[]): Promise<void> {
	try {
		await mkdir(dirPath);
		created.push(dirPath);
	} catch (error) {
		if (!isFileSystemError(error) || error.code !== "EEXIST") {
			throw error;
		}

		const metadata = await stat(dirPath);
		if (!metadata.isDirectory()) {
			throw new Error(`Expected ${dirPath} to be a directory.`);
		}
		existing.push(dirPath);
	}
}

async function writeMissingFile(
	filePath: string,
	content: string,
	created: string[],
	existing: string[],
): Promise<void> {
	try {
		const handle = await open(filePath, "wx", 0o600);
		try {
			await handle.writeFile(content, "utf-8");
		} finally {
			await handle.close();
		}
		created.push(filePath);
	} catch (error) {
		if (!isFileSystemError(error) || error.code !== "EEXIST") {
			throw error;
		}

		const metadata = await stat(filePath);
		if (!metadata.isFile()) {
			throw new Error(`Expected ${filePath} to be a file.`);
		}
		existing.push(filePath);
	}
}

async function syncDirectory(dirPath: string): Promise<void> {
	let handle: FileHandle | undefined;
	try {
		handle = await open(dirPath, "r");
		await handle.sync();
	} catch (error) {
		if (!isIgnorableDirectorySyncError(error)) {
			throw error;
		}
	} finally {
		await handle?.close();
	}
}

async function removeTempFile(tempFile: string): Promise<void> {
	try {
		await unlink(tempFile);
	} catch (error) {
		if (!isFileSystemError(error) || error.code !== "ENOENT") {
			throw error;
		}
	}
}

function isFileSystemError(error: unknown): error is FileSystemError {
	return error instanceof Error;
}

function isIgnorableDirectorySyncError(error: unknown): boolean {
	return (
		isFileSystemError(error) &&
		(error.code === "EISDIR" ||
			error.code === "EINVAL" ||
			error.code === "ENOTSUP" ||
			error.code === "EPERM" ||
			error.code === "EACCES")
	);
}
